name: Release
on:
  push:
    branches: [main]
permissions:
  contents: write
  packages: write
jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v4
        with:
          go-version: "1.21.0"
      - name: Build
        run: make build
      - name: Create tag
        id: tag
        run: |
          TAG=v$(date +%Y%m%d%H%M%S)
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          git tag $TAG
          git push origin $TAG
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./bin/rtt
          name: Release ${{ steps.tag.outputs.tag }}
          draft: false
          prerelease: false
          tag_name: ${{ steps.tag.outputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.RTT_TOKEN }}
